//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crom.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlTags {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlTags() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crom.Controls.XmlTags", typeof(XmlTags).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowedDock.
        /// </summary>
        internal static string TagAllowedDock {
            get {
                return ResourceManager.GetString("TagAllowedDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentDock.
        /// </summary>
        internal static string TagCurrentDock {
            get {
                return ResourceManager.GetString("TagCurrentDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentMode.
        /// </summary>
        internal static string TagCurrentMode {
            get {
                return ResourceManager.GetString("TagCurrentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string TagForm {
            get {
                return ResourceManager.GetString("TagForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        internal static string TagForms {
            get {
                return ResourceManager.GetString("TagForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        internal static string TagGuid {
            get {
                return ResourceManager.GetString("TagGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string TagHeight {
            get {
                return ResourceManager.GetString("TagHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAutoHide.
        /// </summary>
        internal static string TagIsAutoHide {
            get {
                return ResourceManager.GetString("TagIsAutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSelected.
        /// </summary>
        internal static string TagIsSelected {
            get {
                return ResourceManager.GetString("TagIsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentGuid.
        /// </summary>
        internal static string TagParentGuid {
            get {
                return ResourceManager.GetString("TagParentGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string TagWidth {
            get {
                return ResourceManager.GetString("TagWidth", resourceCulture);
            }
        }
    }
}
